spring:
  application:
    name: wd-backend
  datasource:
    url: jdbc:mysql://${RDS_URL}:3306/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "loggers, health, metrics"
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
